# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Fuad Khairi Hamid
title: Senior Mobile Developer
email: fuad@octopus.co.id
website: www.github.com/fuadkhairi

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: fuadkhairi
github_username:  fuadkhairi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: fuadkhairi
linkedin_username: fuadkhairi
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: resume link
  icon: fas fa-globe
  url: fuadkhairi.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fuad and I'm a senior mobile developer. An iOS developer with 3 years of developing iOS Apps and 5 years total of mobile programming experience. Skilled in Swift to develop iOS Apps in XCode. Committed to clean code and continuous learning. Ready to contribute to your projects.

  I am most skilled in: <mark>iOS Development</mark> and since I was an android developer, I still can do <mark>Android Development</mark>, despite not really update with the latest tech. I also doing AI things as my side projects since I was an AI researcher.

content:
  - title: Projects I`ve worked on / Contributed to # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Octopus - Solusi Daur Ulangmu
        additional_links:
          - title:  App Store link for this app
            icon: fab fa-app-store-ios
            url: https://apps.apple.com/us/app/octopus-solusi-daur-ulangmu/id1515879876
          - title:  Play Store link for this app
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.octopus.customer&hl=en_US&pli=1
        quote: >
           Octopus is the first circular economy platform in Indonesia
        description: | # this will include new lines to allow paragraphs
          <img src="/images/octogif.gif" width="148" height="320"> &emsp; <img src="/images/octo1.jpeg" width="148" height="320"> &emsp; <img src="/images/octo2.jpeg" width="148" height="320">
           
          Octopus - Solusi Daur Ulangmu is the customer app of Octopus. I was working to develop feature for this application as solo developer in iOS platform.
      - layout: left
        title: MyBluebird Taxi
        additional_links:
          - title:  App Store link for this app
            icon: fab fa-app-store-ios
            url: https://apps.apple.com/id/app/mybluebird-taxi/id476533261
          - title:  Play Store link for this app
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.seatech.bluebird&hl=en_US
        quote: >
           Bluebird is the largest taxi operator company in Indonesia
        description: | # this will include new lines to allow paragraphs
          <img src="/images/bb1.jpeg" width="148" height="320"> &emsp; <img src="/images/bb2.jpeg" width="148" height="320"> &emsp; <img src="/images/bb3.jpeg" width="148" height="320">
           
          I've joined bluebird group as iOS Developer at Marketing Squad. I've got involved into the development of transforming old MyBB5 to MyBB6 with fresh look. My responsibility is to deliver marketing features such as configurable top banner slideshow and recommendations section in homepage, also the new promo inbox. All of them is using Clevertap SDK to deliver the data. I also do 3rd party sdk integration like clevertap, firebase, etc., Deeplink integration, to events for user analysis.
      - layout: left
        title: Praktek dr. Bob
        additional_links:
          - title:  App Store link for this app
            icon: fab fa-app-store-ios
            url: https://apps.apple.com/id/app/praktek-dr-bob/id1534862547
          - title:  Play Store link for this app
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.carakde.dokterbob&hl=id&gl=US
        quote: >
           Praktek dr. Bob is ticket ordering apps at dr. Bob clinic
        description: | # this will include new lines to allow paragraphs
          <img src="/images/bob0.jpeg" width="148" height="320"> &emsp; <img src="/images/bob1.jpeg" width="148" height="320"> &emsp; <img src="/images/bob2.jpeg" width="148" height="320">
           
          My responsibily is to deliver features update, bug fixing, and app deployment to app store. Feature I've worked on such as multiple login system with whatsapp, facebook, google, and apple.
  - title: My Experiments Project / Side Projects / Other projects
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Waste Classification - Octopus Extension (2023)
        quote: >
           Detect and classify waste type with Apple's MLKIt
        description: | # this will include new lines to allow paragraphs
          <img src="/images/waste_classification.gif" width="148" height="320">
           
          Detect and classify waste type using apple's MLKit, embedding the classifier model to Octopus customer app for research purpose. I am using CreateML of XCode to create and training waste classifier model using dataset from Octopus, then use the CoreML framework to load the model then use it to classify waste using iPhone's camera in realtime.
      - layout: left
        title: Jellyfish Detection and Classification with Neural Network (2019)
        quote: >
           Detect and classify jellyfish from video or camera.
        description: | # this will include new lines to allow paragraphs
          <img src="/images/jellyfish.jpeg" width="320" height="180">
           
          Detect and classify jellyfish from video or camera using YOLOv3 neural network models, trained using custom jellyfish dataset in Python.
      - layout: left
        title: Gaia Jaya (2018)
        quote: >
           Gaiya Jaya is android based mini games developed using C# with Unity
        description: | # this will include new lines to allow paragraphs
          <img src="/images/gaia.jpeg" width="640" height="180">
           
          This game aims is to increase people awareness about how to dispose of waste properly without polluting the environment
      - layout: left
        title: Sky Children (2018)
        quote: >
           Sky Children is endless jumping game release on android & tizen, developed with C# Unity
        description: | # this will include new lines to allow paragraphs
          <img src="/images/sky1.jpeg" width="180" height="320"> &emsp; <img src="/images/sky2.jpeg" width="200" height="320">
           
          Sky Children developed with C# Unity, and I use open source assets (I am just writing the code), and then release the game to play store (not available now, not updating the app so get unlisted) and also in Tizen (got thousand of download there) and won prize from Dicoding developer program for Tizen Developer
      - layout: left
        title: AFI (Application for Intelligence) (2019)
        quote: >
           Android based application to classify kids intelligent type, written in Java
        description: | # this will include new lines to allow paragraphs
          <img src="/images/afi.jpeg" width="320" height="240">
           
          Application For Intelligence (AFI) is my personal project to do early classification for kids intelligence type by answering questionare. The app is developed using Java as programming language and standard MVC design pattern.
      - layout: left
        title: Coop2Coop (2019)
        quote: >
           Android based application for cooperation marketplace (prototype)
        description: | # this will include new lines to allow paragraphs
          <img src="/images/coop.jpeg" width="320" height="190">
           
          This cooperation marketplace prototype is written in Java and using MVP design pattern (the projects is discontinued)
      - layout: left
        title: Door Lock Controller (2018)
        quote: >
           Android based application to open / close door using thingspeak server
        description: | # this will include new lines to allow paragraphs
          <img src="/images/door.jpeg" width="320" height="250">
           
          Door lock controller is an android app written in Java to open/close the door. This app is connected to thingspeak server and will control an iot device (forget is it a rasppi or arduino) to open/close the door
      - layout: left
        title: E-Data Logistic (2018)
        quote: >
           Android based application for to predict logistic data using machine learning
        description: | # this will include new lines to allow paragraphs
          <img src="/images/edata.jpeg" width="320" height="275">
           
          This app is written in Java and using python to develop machine learning model to make prediction based on given data, then show the data to mobile application.
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Octopus Indonesia
        link: octopus.co.id/id
        # link_text: boringcompany.com
        sub_title: Senior Mobile Developer (iOS)
        caption: January 2023 - Present
        quote: >
          Deliver features for Octopus iOS Customer Application
        description: | # this will include new lines to allow paragraphs
            Some of responsibility:
                • Responsible to maintain iOS Octopus apps crash-free rate >96%
                • Implement CI/CD
                • Write Unit test, and increase code coverage to 50%
                • Developed intuitive user interface and engaging user experience that resulted in positive user feedback
                • Implement MVVM Design Pattern with RxSwift
                • Stand by for fatal production bugs to replicate and fix on the next release
      - layout: left
        link: octopus.co.id/id
        sub_title: Mobile Developer
        caption: June 2020 - August 2021
        quote: >
          Deliver features for Octopus Apps in iOS, Android, and Web App (Flutter)
        description: | # this will include new lines to allow paragraphs
            Some of responsibility:
                • Develop feature and manage release of Octopus apps in iOS (Customer app) and Android (Customer, Pelestari, and Waste Bank app) platform
                • Develop Octopus mobile web app in Flutter in order to collaborate with Grab Application
                • Implement MVVM design pattern in iOS and Android
      - layout: left
        link: octopus.co.id/id
        sub_title: Android Developer
        caption: December 2019 - June 2020
        quote: >
          Working on Octopus Android Apps, and testing on the field (with pelestari)
        description: | # this will include new lines to allow paragraphs
            Some of responsibility:
                • Responsible for developing features of Octopus Android Apps, includes Octopus User Apps, Pelestari Apps, and Agent Apps, and make sure the flow of the alpha app is working.
      - layout: left
        title: PT. Bluebird Group Tbk.
        link: bluebirdgroup.com
        # link_text: boringcompany.com
        sub_title: iOS Developer
        caption: August 2021 - December 2022
        quote: >
          Joined the marketing squad to support marketing features on Bluebird Taxi iOS app
        description: | # this will include new lines to allow paragraphs
            Some of responsibility:
                • Responsible to develop and integrate marketing-based feature such as promotion inbox,
                  deep links, events, and home page marketing contents in Bluebird iOS App.
                • Responsible to integrate some third-party tools and its features for marketing purpose
                  such as Clevertap, Firebase, Facebook, and Google SDK
                • Actively communicate with core app team to deliver features from marketing team for
                  release.
      - layout: left
        title: The Gym Pod (EngX1)
        link: engx1.com
        # link_text: boringcompany.com
        sub_title: Android Developer
        caption: July 2021
        quote: >
          Joined the gym pod team.
        description: | # this will include new lines to allow paragraphs
            Some of responsibility:
                • Responsible to transform a React Native Mobile Application to Native Android that works on smart mirror using clean architecture and mvvm pattern.
      - layout: left
        title: PT. Carakde Solusi Informatika
        link: carakde.id
        # link_text: boringcompany.com
        sub_title: Mobile Developer (Android/iOS)
        caption: August 2018
        quote: >
          Code few apps in android and iOS platform
        description: | # this will include new lines to allow paragraphs
            Some of responsibility:
                • Code and deliver a few end-to-end Android Mobile Application with MVVM and Agile Process
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hasanuddin University
        caption: 2015 - 2019
        sub_title: BSc Computer Science / Informatics Engineering
        quote: >
          Hasanuddin University which is abbreviated as Unhas, is one of the largest autonomous universities in Indonesia. It is located in Makassar, South Sulawesi, Indonesia.
        description: | # this will include new lines to allow paragraphs
          During my time at Hasanuddin I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          On the end of my study, I spent a lot of my time as a researcher on AIMP (Artificial Intelligence and Multimedia Processing) Labs to learn about AI and Machine Learning.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mobile software engineering some of my other interests and hobbies are:
      - Badminton
      - Gaming
      - Novel reading


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
